import numpy as np
import pandas as pd

# A file with the constants such as colors etc. # Config vars below

HOLLOWING_COLOR = [np.uint8(n) for n in [1, 1, 128, 70]]
HOUSE_COLOR = [np.uint8(n) for n in [247, 114, 30, 128]]
OVERLAP_COLOR = [np.uint8(n) for n in [1, 1, 200, 200]]
IMAGE_SIZE = 800


# These limits were set by the in house subjects experts at Bolius
CONDUCTIVITY_LIMITS = {
    "low": 150,  # You have high risk if below this
    "medium": 350,  # You have medium risk if you are above low limit but below this
}


# Generated by colormap on http://miljoegis.mim.dk/spatialmap?profile=miljoegis-klimatilpasningsplaner&layers=theme-gst-dtkskaerm_daempet
CONDUCTIVITY_MAPPING = pd.DataFrame(
    {
        "50": np.array([12, 47, 122]),
        "100": np.array([15, 66, 128]),
        "125": np.array([17, 81, 130]),
        "150": np.array([20, 101, 135]),
        "200": np.array([23, 119, 140]),
        "250": np.array([28, 139, 145]),
        "275": np.array([31, 150, 141]),
        "325": np.array([31, 161, 132]),
        "375": np.array([27, 171, 118]),
        "425": np.array([22, 181, 99]),
        "475": np.array([16, 194, 79]),
        "525": np.array([9, 204, 46]),
        "600": np.array([4, 214, 13]),
        "650": np.array([25, 222, 1]),
        "725": np.array([62, 227, 2]),
        "800": np.array([101, 232, 2]),
        "900": np.array([144, 240, 0]),
        "975": np.array([184, 245, 3]),
        "1075": np.array([229, 250, 0]),
        "1175": np.array([252, 244, 3]),
        "1300": np.array([250, 229, 7]),
        "1400": np.array([247, 212, 13]),
        "1550": np.array([245, 198, 13]),
        "1700": np.array([240, 180, 12]),
        "1850": np.array([237, 168, 19]),
        "2050": np.array([235, 156, 20]),
        "2200": np.array([227, 138, 30]),
        "2400": np.array([219, 122, 37]),
        "2650": np.array([214, 111, 44]),
        "2900": np.array([207, 99, 50]),
        "3350": np.array([199, 89, 56]),
    },
    index=["Red", "Green", "Blue"],
).transpose()
